language: java
jdk:
- oraclejdk8
before_script: echo ${TRAVIS_BUILD_NUMBER} && echo ${TRAVIS_BUILD_NUMBER} >src/main/resources/version.txt
install: true
services:
- mongodb
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
  - istvan.marhefka@gmail.com
