language: java
jdk:
- oraclejdk8
before_script: echo ${TRAVIS_BUILD_NUMBER} && echo ${TRAVIS_BUILD_NUMBER} >src/main/resources/version.txt
install: true
deploy:
  provider: cloudfoundry
  api: https://api.draco-812.appcloud.swisscom.com
  username: istvan.marhefka@gmail.com
  password:
    secure: H9EVNCT+k/SFgbG4Mnuvd+a4iyax6DVyWJblL+JZ7fwe561AZdtLBvczwXNcQHYWDzt6NguquHxTPefODeaqKo/B31CoZM/sxkYPY+dGwtVrgVp6cSeo4P3BMsU/hcGwZFOnfHi8k7DkEZDKGUuKz9v7UMt1s8e7ve+05rGT6kee5FoF4S6LR07yn0+piucINT/EhlW8Ngk4d0ObFlOmIF6DvXlVGDkriwmdxEndxtZxqfs7jlkR0QWCYu79nckzcY69js35w3v5BV8+wdiPBZW5nr0nbTarSwtK0rfATuBZ2Gibmj4Fo08gQKl/Npx922hjXPnhQC+kCdyo2s753PnDIgOWSsLRdT5vWe5F+P6coXeROUiy5/dvV8MQ7oKcFk7pJrTkiuWBKcOh4cX7N5LNxmhRlluxaRa4F8cGqS8HZSlpccPT49QU/TryxXH4PQholTtbJMtS59ZLXKucFYqP1XkCrohq4Uooymoml+ZiFXzxDXA553NANsI3xpSCTuWufAirFU8TfyxbdBxMYLdIRCus8SDQ4BWud7KgaMfAhLryGewg1Qdi1JFPpZfTWcv/RMF5bdxrxbqHB7Ltmk/AmQF922XVUCicIcP2Lz+RJjvb5DS24WZ10V1tsZoSaZqq/cYPsiSpyp+3wL2bZC+Xu0F1BnaBNF8PLbrQ6ME=
  organization: tddblog.hu
  space: development
  on:
    repo: marhefka/calculator
services:
- mongodb
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
  - istvan.marhefka@gmail.com
