language: java
jdk:
- oraclejdk8
before_script: echo ${TRAVIS_BUILD_NUMBER} && echo ${TRAVIS_BUILD_NUMBER} >src/main/resources/version.txt
install: true
deploy:
  edge: true
  provider: cloudfoundry
  username: istvan.marhefka@gmail.com
  password:
    secure: BfA3t8kdwCSOoMLMgGgMEp0ASbN/Jbg7H/Z24H+XbmGwIq7cZp1Hirw9EPy/ntvvJ+vocPMb8MLvgr1CVGy4w28OhWUgjL2CwonEsHXlH0NQGB4C+HpyL8Aycl5qIEUQ1J4doydHckjvugCrovSWyaEYFDEoOp4ZpIveJYZCRi6tgZpOtpe7mcYPEpDDCyHbc5DrKaCLz82TdSNFajkaofpztM6uhkMMEOdpECZvRiSfcWUyQnpvHZMyeITSBfY3HkE3HCVpphg5KOMZ1S489NtVxHT4XdURkgL6UhC6ovdI3dXzGhB+tKgvuo86TyB+Samt8CuoIxX0A+KJ8dkmo1mPZ6IdKFBhImmBCcUHcDY+5GGy4mr4OQs24vMoKIUbcS7xk256jP6qQVvCXEAkE0Yvj720/GCFZTAYMWfBaghAuo/apo9qLhQI9Cd6Nm41eDiuIh5rXMAdYeA6LNifeM/J0KwoPiXa2DPkHOtianVhAskbPeMJRA+fxToxnN8lKENm6lYOM/CsNGNSJx7JBaduEpIsa2Z0JGFBJsuu1DIumFeLX6caEmD7w9eWq4X4DYbWAXAw+IQfzLogF3GLPCY3dk7YT0qW9cHVipwT2TqUZPfp1S702ScdD2NfMU0nC6OMgkE8fvs+UH2EsH895x8Fd7iOzLkWLH+8kD6WDvg=
  api: https://api.run.pivotal.io
  organization: tddblog.hu
  space: development
services:
- mongodb
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
  - istvan.marhefka@gmail.com
