# Application specific config

mongo:
  uri: mongodb://localhost:27017/hello_prod
  clientPoolSize: 10

# Dropwizard config

server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  level: WARN
  loggers:
    org.tddblog.calculator: INFO
  appenders:
    - type: console
