# Application specific config

mongo:
  uri: mongodb://localhost:27017/test
  clientPoolSize: 1

# Dropwizard config

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
      type: http
      port: ${PORT:-9000}

logging:
  level: INFO
  appenders:
    - type: console
